const fs = require('fs');
const path = require('path');

/**
 * Design System Tokens
 * Based on takayaso.com design system
 */

// Colors
const colors = {
  gray: {
    50: '#fafafa', 100: '#f5f5f5', 200: '#e5e5e5', 300: '#d4d4d4', 400: '#a3a3a3',
    500: '#737373', 600: '#525252', 700: '#404040', 800: '#262626', 900: '#171717',
  },
  background: { light: '#ffffff', dark: '#0a0a0a' },
  foreground: { light: '#171717', dark: '#ededed' },
  brand: { twitter: '#60a5fa', instagram: '#ec4899', note: '#22c55e', github: '#404040' },
  success: { light: '#86efac', DEFAULT: '#22c55e', dark: '#16a34a' },
  warning: { light: '#fde047', DEFAULT: '#eab308', dark: '#ca8a04' },
  error: { light: '#fca5a5', DEFAULT: '#ef4444', dark: '#dc2626' },
  white: '#ffffff',
  black: '#000000',
};

// Typography
const fontFamily = {
  sans: 'Lato, "Noto Sans JP", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  mono: 'Lato, monospace',
};
const fontSize = {
  xs: '0.75rem', sm: '0.875rem', base: '1rem', lg: '1.125rem', xl: '1.25rem',
  '2xl': '1.5rem', '3xl': '1.875rem', '4xl': '2.25rem', '5xl': '3rem',
};
const fontWeight = { normal: '400', medium: '500', semibold: '600', bold: '700' };
const lineHeight = { none: '1', tight: '1.25', snug: '1.375', normal: '1.5', relaxed: '1.625', loose: '2' };
const letterSpacing = { tighter: '-0.05em', tight: '-0.025em', normal: '0em', wide: '0.025em', wider: '0.05em' };

// Spacing
const spacing = {
  0: '0', px: '1px', 0.5: '0.125rem', 1: '0.25rem', 1.5: '0.375rem', 2: '0.5rem',
  2.5: '0.625rem', 3: '0.75rem', 3.5: '0.875rem', 4: '1rem', 5: '1.25rem',
  6: '1.5rem', 7: '1.75rem', 8: '2rem', 9: '2.25rem', 10: '2.5rem',
  11: '2.75rem', 12: '3rem', 14: '3.5rem', 16: '4rem', 20: '5rem',
  24: '6rem', 28: '7rem', 32: '8rem',
};
const borderRadius = {
  none: '0', sm: '0.125rem', DEFAULT: '0.25rem', md: '0.375rem', lg: '0.5rem',
  xl: '0.75rem', '2xl': '1rem', '3xl': '1.5rem', full: '9999px',
};
const borderWidth = { 0: '0', DEFAULT: '1px', 2: '2px', 4: '4px', 8: '8px' };

// Shadows
const boxShadow = {
  none: 'none',
  sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
  DEFAULT: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
  md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
  lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
  xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
  '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
  inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
};

// Transitions
const transitionDuration = { fast: '200ms', DEFAULT: '300ms', slow: '500ms', entrance: '1000ms' };
const transitionTimingFunction = { DEFAULT: 'ease-out', linear: 'linear', in: 'ease-in', inOut: 'ease-in-out' };

// Breakpoints
const breakpoints = { sm: '640px', md: '768px', lg: '1024px', xl: '1280px', '2xl': '1536px' };

function flattenObject(obj, prefix = '') {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const newKey = prefix ? `${prefix}-${key}` : key;
    if (typeof value === 'object' && value !== null) {
      Object.assign(result, flattenObject(value, newKey));
    } else {
      result[newKey] = value;
    }
  }
  return result;
}

function generateCSSVariables() {
  const sections = [
    { name: 'Colors', prefix: 'color', tokens: flattenObject(colors) },
    { name: 'Font Family', prefix: 'font-family', tokens: fontFamily },
    { name: 'Font Size', prefix: 'font-size', tokens: fontSize },
    { name: 'Font Weight', prefix: 'font-weight', tokens: fontWeight },
    { name: 'Line Height', prefix: 'line-height', tokens: lineHeight },
    { name: 'Letter Spacing', prefix: 'letter-spacing', tokens: letterSpacing },
    { name: 'Spacing', prefix: 'spacing', tokens: flattenObject(spacing) },
    { name: 'Border Radius', prefix: 'radius', tokens: borderRadius },
    { name: 'Border Width', prefix: 'border-width', tokens: borderWidth },
    { name: 'Box Shadow', prefix: 'shadow', tokens: boxShadow },
    { name: 'Transition Duration', prefix: 'duration', tokens: transitionDuration },
    { name: 'Transition Timing', prefix: 'ease', tokens: transitionTimingFunction },
    { name: 'Breakpoints', prefix: 'breakpoint', tokens: breakpoints },
  ];

  let css = `/**
 * Design System Tokens - CSS Variables
 * Based on takayaso.com design system
 * Auto-generated by build-css.js
 */

:root {
`;

  for (const section of sections) {
    css += `\n  /* ${section.name} */\n`;
    for (const [key, value] of Object.entries(section.tokens)) {
      const varName = key === 'DEFAULT' ? `--${section.prefix}` : `--${section.prefix}-${key}`;
      css += `  ${varName}: ${value};\n`;
    }
  }

  css += `}

/* Dark mode */
@media (prefers-color-scheme: dark) {
  :root {
    --color-background: var(--color-background-dark);
    --color-foreground: var(--color-foreground-dark);
  }
}

/* Keyframe animations */
@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}

@keyframes slideUp {
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
}

@keyframes scaleIn {
  from { opacity: 0; transform: scale(0.95); }
  to { opacity: 1; transform: scale(1); }
}

.animate-fadeIn { animation: fadeIn var(--duration) var(--ease); }
.animate-slideUp { animation: slideUp var(--duration) var(--ease); }
.animate-scaleIn { animation: scaleIn var(--duration) var(--ease); }
`;

  return css;
}

const distDir = path.join(__dirname, '..', 'dist');
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

fs.writeFileSync(path.join(distDir, 'tokens.css'), generateCSSVariables());
console.log('Generated dist/tokens.css');
